# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deepcab.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "deepcab.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rdeepcab.proto\x12\x07\x64\x65\x65pcab"\xa6\x01\n\nFeatureRow\x12\x17\n\x0fpickup_datetime\x18\x01 \x01(\t\x12\x18\n\x10pickup_longitude\x18\x02 \x01(\x01\x12\x17\n\x0fpickup_latitude\x18\x03 \x01(\x01\x12\x19\n\x11\x64ropoff_longitude\x18\x04 \x01(\x01\x12\x18\n\x10\x64ropoff_latitude\x18\x05 \x01(\x01\x12\x17\n\x0fpassenger_count\x18\x06 \x01(\x05"2\n\x0ePredictRequest\x12 \n\x03row\x18\x01 \x01(\x0b\x32\x13.deepcab.FeatureRow"\x95\x01\n\x0fPredictResponse\x12\x0c\n\x04\x66\x61re\x18\x01 \x01(\x01\x12\x1b\n\x0einterval_lower\x18\x02 \x01(\x01H\x00\x88\x01\x01\x12\x1b\n\x0einterval_upper\x18\x03 \x01(\x01H\x01\x88\x01\x01\x12\x14\n\x0c\x62\x61\x63kend_kind\x18\x04 \x01(\tB\x11\n\x0f_interval_lowerB\x11\n\x0f_interval_upper2N\n\x0ePredictService\x12<\n\x07Predict\x12\x17.deepcab.PredictRequest\x1a\x18.deepcab.PredictResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "deepcab_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FEATUREROW"]._serialized_start = 27
    _globals["_FEATUREROW"]._serialized_end = 193
    _globals["_PREDICTREQUEST"]._serialized_start = 195
    _globals["_PREDICTREQUEST"]._serialized_end = 245
    _globals["_PREDICTRESPONSE"]._serialized_start = 248
    _globals["_PREDICTRESPONSE"]._serialized_end = 397
    _globals["_PREDICTSERVICE"]._serialized_start = 399
    _globals["_PREDICTSERVICE"]._serialized_end = 477
# @@protoc_insertion_point(module_scope)
