apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deepcab-prod
resources:
  - ../../base
images:
  - name: europe-west1-docker.pkg.dev/PROJECT/deepcab/api
    newName: europe-west1-docker.pkg.dev/PROJECT/deepcab/api
    newTag: latest   # overridden by CI via `kustomize edit set image ...`
